### ISSUE TITLE
Remove <p> produced by  markdownify

### ISSUE THREAD

**Issue by bep** [spf13/hugo#1025]
See http://discuss.gohugo.io/t/markdown-in-front-matter/1004/2

**Comment by robsonsobral** [comment]
It wasn't a good idea.

Now, we have to code `<p>{{ . | markdownify }}</p>`, which could be fine until you add some other block level elements. Example:

````yaml
sections:
  -
    content: |
    
      ### subtitle

      lorem ipsum
```

To wrap everything into a `p` isn't a behavior of blackfriday only. Other markdown engines do that too.

Thank you.
