### ISSUE TITLE
Why table not gernerated from my markdown file?

### ISSUE THREAD

**Issue by fzx** [spf13/hugo#1245]
example:

Item     | Value
-------- | ---
Computer | $1600
Phone    | $12
Pipe     | $1

My config.yaml like this:
```
BaseUrl: "localhost"
LanguageCode: "zh-cn"
Title: ""

blackfriday:
    extensions:
      - hardLineBreak

Params:
  Author: "fangzx"
  DateForm: "2006-01-02"
  ShowRelatedPost: False
  SyntaxHighlightTheme: "solarized_dark.min.css"

Indexes:
  tag: "tags"

permalinks:
  post: /blog/:year/:month/:day/:title/

MetadataFormat: "yaml"
```
