### ISSUE TITLE
Enhance default Menu sorting

### ISSUE THREAD

**Issue by moorereason** [spf13/hugo#1562]
The default Menu sorting only considers `Weight` and `Name` ([see here](https://github.com/spf13/hugo/blob/252ea96d1d359b485bae489327a8219d102f0607/hugolib/menu.go#L139)).  We should add `Identifier` (and potentially `URL`) as an additional criteria so that entries like the following will have deterministic sorting:

```toml
[[menu.social]]
    pre = "<i class='fa fa-twitter'></i>"
    url = "http://www.twitter.com/example"
    identifier = "twitter"
```
See [discussion forum](http://discuss.gohugo.io/t/how-to-get-hugo-to-not-update-unchanged-files/2020) for more details about why the sorting could be non-deterministic.
