### ISSUE TITLE
jekyll convert: Support front matter defaults

### ISSUE THREAD

**Issue by joneskoo** [spf13/hugo#1623]
I don't think convert supports front matter defaults. When I tried to convert my jekyll site, it converted 0 pages and gave me no clues as to what went wrong. When I converted my blog path separately, I got content converted, but not config. Not sure if that's how it's supposed to work or not.

http://jekyllrb.com/docs/configuration/#front-matter-defaults

This is what I had in _config.yml in jekyll:

```
defaults:
  -
    scope:
      path: "blog"
    values:
      layout: "post"
```
