### ISSUE TITLE
Hugo generating empty Taxonomy pages

### ISSUE THREAD

**Issue by wazoo** [spf13/hugo#1707]
Using the example here:

http://gohugo.io/templates/terms/

I have the following template:

```erb
{{ partial "header" . }}
{{ partial "top_nav" . }}
<div class="maincontainer">
  <div class="row">
    <div class="col-md-8">
        <div class="blog-post">
          <div class="blog-post-title">
            <h2>
              {{ .Title }}
            </h2>
          </div>
          <div class="blog-post-body">
            <ul>
              {{ $data := .Data }}
              {{ range $key, $value := .Data.Terms }}
                <li><a href="{{ $key | urlize }}">{{ $key }}</a></li>
              {{ end }}
            </ul>
          </div>
        </div>

    </div>
    <div class="col-md-4">
      {{ partial "sidebar/default_container" . }}
    </div>
  </div>
</div>
{{ partial "footer" . }}
```
Located at layouts/default/terms.html and layouts/default/terms.html (they are the same while troubleshooting) and the taxonomy pages are all rendering blank.  

When I try to just do {{ .Data }} on that page I get something like 'map[tag:[{0 }] Singular:tag Plural:tags Pages:[]]' which looks like its empty (doing {{ .Data.Terms }} displays nothing).  

Hugo does render all of the pages for all of the taxonomy terms so they seem to be set up correctly but just in case this is how I am defining them:

config.yaml
```yaml
taxonomies:
    tag: "tags"
    topic: "topics"
```
fontmatter
```yaml
---
title: "Title"
date: "2015-12-15"
author: "ben"
summary: ""
topics:
  - Topic
  - Topic
  - Topic
tags: [tag,tag,tag,tag]
---
```
I am using two different array styles because posts usually have more tags than topics so I wanted to save some room but that shouldn't make a difference.  

The live site with a blank taxonomy is here: https://www.beyondvm.com/topics/home-lab/
This is a post that should show up on that page: https://www.beyondvm.com/2014/01/intel-avoton-the-perfect-home-lab-host/
here is the fontmatter for that page:
```yaml
---
title: "Intel Avoton: The Perfect Home Lab Host?"
date: 2014-01-31
author: "ben"
summary: ""
topics:
  - Articles
  - Home Lab
  - Lab
  - Whitebox
tags: [lab,hardware,homelab]
draft: false
comments: true
---
```
If its helpful, this is the output when hugo builds the site:

```
Change detected, rebuilding site
2015-12-15 13:08 -0700
0 of 3 drafts rendered
0 future content
15 pages created
0 paginator pages created
32 tags created
14 topics created
in 99 ms
```
Any help would be appreciated, I am not sure if this is a bug or not but it seems like it (maybe a doc bug).
