### ISSUE TITLE
Wercker Hugo build error : function "readDir" not defined

### ISSUE THREAD

**Issue by ysqi** [spf13/hugo#1794]
hi, @spf13 , Hugo document build error at wercker, but work well in my pc (Hugo v0.15)

**error info**
2016/01/25 template: shortcodes/fileindex.html:7: function "readDir" not defined
panic: runtime error: invalid memory address or nil pointer dereference

error detail : https://gist.github.com/ysqi/d212166b173b0f81f679

**wercker.yml**
see: https://github.com/ysqi/hugodocument
```yml
build:
  box: samueldebruyn/hugo-build
  steps:
    - script:
        name: initialize git submodules
        code: |
            git submodule update --init --recursive
    - arjen/hugo-build:
        prod_branches: master
```
