### ISSUE TITLE
helpers: EXTENSION_BACKSLASH_LINE_BREAK is missing for Blackfriday

### ISSUE THREAD

**Issue by heavywatal** [spf13/hugo#1935]
I want to enable `EXTENSION_BACKSLASH_LINE_BREAK` of blackfriday. But the following config does not work:

```toml
[blackfriday]
extensions = ["backslashLineBreak"]
```

There seems no such entry in `blackfridayExtensionMap` in `helpers/content.go`. Can it be fixed?
