### ISSUE TITLE
Feature request: extend post frontmatter with data files

### ISSUE THREAD

**Issue by fj** [spf13/hugo#2135]
This is a follow-up to a support thread about [using datafiles to extend page frontmatter](https://discuss.gohugo.io/t/customizing-hugos-slug-inference-with-datafiles/3287/9):

> A datafile to filename override mechanism would be easy to implement, but it sounds like a very special use case, so probably not worth it.

The primary use cases and goals include:
- You want to extend different posts with different metadata for different environments. For example, in a staging environment, you may generate a data file in one way, but in a production environment you may use another. By providing different datafiles (rather than editing N posts each time) you can keep your post frontmatter minimal and clean.
- You want to avoid many edits to many files to make small but sweeping changes, so that your source-control history remains an accurate reflection of the state of your project.

The desirable features are:
- Hugo defines a mechanism whereby you can specify keys which are merged with the front-matter for a post or set of posts from `.Data`. One file might contain many such overrides. For example, a hypothetical specification could be:

```

---
__content:
  applies:
    - posts/elephant.markdown
    - posts/ocelot.markdown
    - posts/zebra.asciidoc
  frontmatter:
    tags:
      - animals
      - science

---
```
- The mechanism may also be employed to apply the same keys to many posts at once, as in the example above.
- Data trumps frontmatter. If you define a key in both data and frontmatter, data wins.
