### ISSUE TITLE
RelPermalink is broken in 0.16

### ISSUE THREAD

**Issue by pavanpodila** [spf13/hugo#2276]
As per the [documentation](http://gohugo.io/content/front-matter/#optional-variables), the url for a post is driven by the filename, if `url` or `slug` is missing. However that does not seem to be the case and instead the url is being constructed out of the `title` in the front matter.

For example:

If I have post named: `content/post/2016-05-31-building-courses-for-tuts.md`, which has the following front matter:

```yml
---
date: "2016-05-31T08:53:06-04:00"
title: "Building Courses for Tuts+"
---

```

the resulting `RelPermalink` is generated as `http://localhost:1313/2016/05/building-courses-for-tuts+`

As you can see, It is not respecting the filename. The correct url should be __`http://localhost:1313/2016/05/building-courses-for-tuts/`__
