### ISSUE TITLE
Renamed taxonomy doesn't show content

### ISSUE THREAD

**Issue by digitalcraftsman** [spf13/hugo#2465]
*Again  shown with my [demo setup](https://github.com/digitalcraftsman/hugo-multilingual).*

I want to rename the default taxonomy categories in the German version to "kategorien". I added the following snippet to the config file:

```toml
[languages.de.taxonomies]
        category = "kategorien"
```

I can access [http://localhost:5000/de/kategorien/](http://localhost:5000/de/kategorien/) but no content is shown even if two content files (foo.de.md and bar.de.md) have a category.

Furthermore, I renamed the the category taxonomy for the default content language (en) as well:

```toml
[taxonomies]
    category = "kategorien"
```

Hugo renders a site at [http://localhost:5000/kategorien/](http://localhost:5000/kategorien/) but here are also no pages shown. foo.md and bar.md list a category in their frontmatter.
