### ISSUE TITLE
Hugo 0.18 broke my site; now gives "LinkResolver: No page found for xxx" and 404 errors

### ISSUE THREAD

**Issue by richb-hanover** [spf13/hugo#3026]
My site is a straightforward collection of Markdown pages that worked fine for Hugo 0.16.

Regrettably, our hosting provider has switched to Hugo 0.18, and many (perhaps all) relative links between pages in the Markdown now give message of  `LinkResolver: No page found for xxx`

As stated in #2506, setting `sourceRelativeLinks: false` gets rid of those errors. **But...** 

* Links to files with file suffixes give 404 errors in the browser (but not at compile time with `hugo serve`, e.g., `[Test](/bloat/wiki/Tests_for_Bloat.md)` 
* Links with a closing "/" (and no suffix) work fine -e.g., `[Test](/bloat/wiki/Tests_for_Bloat/)` 

**My question:** Is there a way to make the source files work properly again, without editing off the ".md" for my entire site? Many thanks.

PS #1: This is an update of https://github.com/spf13/hugo/issues/2891 The Git repo there can be cloned to demonstrate the problem.

PS #2: Here's my config.yaml file:
```
baseurl: "https://www.bufferbloat.net/projects/"
languageCode: "en-us"
title: "Bufferbloat.net"
disable404: false
canonifyURLs: true
relativeURLs: false

pluralizeListTitles: false
metadataFormat: yaml
params:
  stylesheets: [ "bootstrap.css", "font-awesome.css", "custom.css" ]
  recentTypes: [ "news", "wiki" ]
author:
  name: The Bufferbloat community
  email: bloat@lists.bufferbloat.net
blackfriday:
  plainIDAnchors: true
  sourceRelativeLinks: false
```
