### ISSUE TITLE
Taxonomy title is URLized with v0.18.1

### ISSUE THREAD

**Issue by yvele** [spf13/hugo#3070]
Let's say I have 

```md
{
  "title": "Hello",
  "taxonomy": ["Foo Bar"],
}

## Hello

World
```

With v0.17, my Taxonomy **page title** were perfect: `"Foo Bar"`.

Now with v0.18.1, the taxonomy page title (`.Title`) is URLized: `"foo-bar"`.

I'm both using `pluralizeListTitles` and `preserveTaxonomyNames`

```toml
pluralizeListTitles = false
preserveTaxonomyNames = true
```

Is this a bug or a misuse? I can't find any other related issue (https://github.com/spf13/hugo/issues/2835 ?)
