### ISSUE TITLE
docs: Create JSON helper for template funcs

### ISSUE THREAD

**Issue by bep** [spf13/hugo#3418]
See #3417

The data is (almost) complete and ready to dump to JSON.

Pseudo-data:

```
namespace:
   collections
   funcs:
      After
        description: "After returns all the items after the first N in a rangeable list."
        aliases: ["after"]
        examples: [["in", "expected"]]
```

Most of the stuff above is straight forward; to get the `description` we would have to run the code through the GoDoc parser, which is doable and a nice-to-have.

The big motivations for the above is:

* To reduce maintenance cost.
* To make sure docs is correct and up-to date
* To make sure the examples are correct (we run them as part of the test suite).

Since we can not create content pages from data, I assume a shortcode could include this in the content pages.

/cc @moorereason @rdwatters
